image: python:latest

services:
  - docker:dind

variables:
  MAGNITUDE_FILE: http://magnitude.plasticity.ai/word2vec/GoogleNews-vectors-negative300.magnitude

stages:
  - Test Python 2
  - Test Python 3
  - Deploy to PyPI

before_script:
  # Setup package manager
  - apt-get update 2>&1 >/dev/null
  - apt-get install curl wget -y
  - apt-get install python-setuptools -y
  - apt-get install python3-setuptools -y
  - apt-get install python-dev -y
  - apt-get install python3-dev -y
  # Install gettext for envsubst
  - apt-get install gettext -y

Test Python 2:
  stage: Test Python 2
  script:
    - wget --quiet http://magnitude.plasticity.ai/word2vec/GoogleNews-vectors-negative300.magnitude
    - wget --quiet http://magnitude.plasticity.ai/word2vec+subword/GoogleNews-vectors-negative300.magnitude -O GoogleNews-vectors-negative300.subword.magnitude
    - wget --quiet http://magnitude.plasticity.ai/word2vec+approx/GoogleNews-vectors-negative300.magnitude -O GoogleNews-vectors-negative300.approx.magnitude
    - python2 setup.py install
    - pip2 install gensim
    - python2 -m pymagnitude.converter -i tests/models/word2vec.txt -o out.magnitude
    - python2 -m pymagnitude.converter -i tests/models/word2vec.bin -o out.magnitude
    - python2 -m pymagnitude.converter -i tests/models/glove.txt -o out.magnitude
    - python2 -m pymagnitude.converter -i tests/models/fasttext.vec -o out.magnitude
    - python2 -m pymagnitude.converter -i tests/models/word2vec.txt -o out.magnitude -s
    - python2 -m pymagnitude.converter -i tests/models/word2vec.bin -o out.magnitude -s
    - python2 -m pymagnitude.converter -i tests/models/glove.txt -o out.magnitude -s
    - python2 -m pymagnitude.converter -i tests/models/fasttext.vec -o out.magnitude -s
    - python2 -m tests.tests -i GoogleNews-vectors-negative300.magnitude -s GoogleNews-vectors-negative300.subword.magnitude -a GoogleNews-vectors-negative300.approx.magnitude

  only:
    - master

Test Python 3:
  stage: Test Python 3
  script:
    - wget --quiet http://magnitude.plasticity.ai/word2vec/GoogleNews-vectors-negative300.magnitude
    - wget --quiet http://magnitude.plasticity.ai/word2vec+subword/GoogleNews-vectors-negative300.magnitude -O GoogleNews-vectors-negative300.subword.magnitude
    - wget --quiet http://magnitude.plasticity.ai/word2vec+approx/GoogleNews-vectors-negative300.magnitude -O GoogleNews-vectors-negative300.approx.magnitude
    - python3 setup.py install
    - pip3 install gensim
    - python3 -m pymagnitude.converter -i tests/models/word2vec.txt -o out.magnitude
    - python3 -m pymagnitude.converter -i tests/models/word2vec.bin -o out.magnitude
    - python3 -m pymagnitude.converter -i tests/models/glove.txt -o out.magnitude
    - python3 -m pymagnitude.converter -i tests/models/fasttext.vec -o out.magnitude
    - python3 -m pymagnitude.converter -i tests/models/word2vec.txt -o out.magnitude -s
    - python3 -m pymagnitude.converter -i tests/models/word2vec.bin -o out.magnitude -s
    - python3 -m pymagnitude.converter -i tests/models/glove.txt -o out.magnitude -s
    - python3 -m pymagnitude.converter -i tests/models/fasttext.vec -o out.magnitude -s
    - python3 -m tests.tests -i GoogleNews-vectors-negative300.magnitude -s GoogleNews-vectors-negative300.subword.magnitude -a GoogleNews-vectors-negative300.approx.magnitude

  only:
    - master

Deploy to PyPI:
  stage: Deploy to PyPI
  script:
    - envsubst < deployment/.pypirc > ~/.pypirc
    - chmod 600 ~/.pypirc
    - python setup.py sdist upload -r pypitest
    - python setup.py sdist upload -r pypi

  only:
    - master
