language: python

matrix:
  include:
    - sudo: required
      services:
        - docker
      env: PIP=pip
    - os: osx
      language: generic
      env: PIP=pip2

script:
  - $PIP install pip setuptools -U
  - $PIP install git+https://github.com/plasticity-admin/cibuildwheel.git@macos-ssl
  - travis_wait 60 cibuildwheel --output-dir wheelhouse
  - ls wheelhouse
  - $PIP install awscli --upgrade
  - aws s3 sync ./wheelhouse/ s3://magnitude.plasticity.ai/wheelhouse/
