language: python

python:
  - "3.6"

matrix:
  include:
    - sudo: required
      services:
        - docker
      env: PIP=pip
    - os: osx
      language: generic
      env: PIP=pip2

script:
  - $PIP install pip -U
  - pip install --user certifi || true
  - pip install certifi || true
  - pip2 install --user certifi || true
  - pip2 install certifi || true
  - pip3 install --user certifi || true
  - pip3 install certifi || true
  - $PIP install cibuildwheel==0.8.0
  - cibuildwheel --output-dir wheelhouse
  - ls wheelhouse
