language: python

python:
  - "3.6"
  
matrix:
  include:
    - sudo: required
      services:
        - docker
      env: PIP=pip
    - os: osx
      language: generic
      env: PIP=pip2

script:
  - $PIP install pip -U
  - $PIP install cibuildwheel==0.8.0
  - cibuildwheel --output-dir wheelhouse
  - ls wheelhouse
